--AppUser
CREATE TABLE AppUser ( 
                    userID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    accountName VARCHAR2(50) NOT NULL,
                    password VARCHAR2(255) NOT NULL);
                    
                   
--BillReminder                    
CREATE TABLE BillReminder ( 
                            remindID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            remindName VARCHAR2(100) NOT NULL UNIQUE,
                            deadline DATE NOT NULL,
                            status VARCHAR2(30) DEFAULT 'Pending',
                            userID NUMBER NOT NULL,
                            CONSTRAINT fk_BillReminder FOREIGN KEY (userID) REFERENCES
                            APPUSER (userID));    
                            

--BillReminderHistory                            
CREATE TABLE BillReminderHistory (
                                    historyID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    remindID NUMBER NOT NULL,
                                    remindName VARCHAR2(100) NOT NULL,
                                    deadline DATE NOT NULL,
                                    status VARCHAR2(30) NOT NULL,
                                    userID NUMBER NOT NULL,
                                    CONSTRAINT fk_BillReminderHistory FOREIGN KEY (userID) REFERENCES
                                    APPUSER (userID));
       
                                    
                                    
--Account                                    
CREATE TABLE Account (
                        accID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        accName VARCHAR2(100) NOT NULL,
                        description VARCHAR2(100),
                        balance NUMBER(12, 2) NOT NULL,
                        createdDate DATE DEFAULT SYSDATE,
                        status VARCHAR2(15) DEFAULT 'Active',
                        initialAmount NUMBER(12, 2) NOT NULL CHECK(initialAmount >=0 ),
                        userID NUMBER NOT NULL,
                        CONSTRAINT fk_Account FOREIGN KEY (userID) REFERENCES
                        APPUSER (userID));
                        
                        

--ExpenseAccount
CREATE TABLE ExpenseAccount (
                            accID NUMBER PRIMARY KEY,
                            expenseCategory VARCHAR2(30) NOT NULL CHECK(expenseCategory IN ('Entertainment', 'BillPayment', 'DailyExpense')),
                            spendingLimit NUMBER DEFAULT 0 NOT NULL CHECK(spendingLimit >= 0),
                            CONSTRAINT fk_ExpenseAccount FOREIGN KEY (accID) REFERENCES ACCOUNT(accID));
                            

--FundAccount
CREATE TABLE FundAccount (
                        accID NUMBER PRIMARY KEY,
                        fundType VARCHAR2(30) NOT NULL CHECK(fundType IN ('LongTermSaving', 'EmergencyFund')),
                        minimumLimit NUMBER DEFAULT 0 NOT NULL CHECK(minimumLimit >=0),
                        CONSTRAINT fk_FundAccount FOREIGN KEY (accID) REFERENCES ACCOUNT(accID));
                        
--SavingGoal
CREATE TABLE SavingGoal (
                        goalID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        goalName VARCHAR2(50) NOT NULL,
                        targetAmmount NUMBER NOT NULL CHECK(targetAmmount > 0),
                        createdDate DATE DEFAULT SYSDATE,
                        deadline DATE NOT NULL,
                        accID NUMBER NOT NULL,
                        CONSTRAINT chk_deadline CHECK (deadline > createdDate),
                        CONSTRAINT fk_SavingGoals FOREIGN KEY (accID) REFERENCES ACCOUNT(accID));
                        
--Transaction
CREATE TABLE AccountTransaction (
                        transID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        transName VARCHAR2(50) NOT NULL,
                        transType VARCHAR2(30)NOT NULL CHECK(transType IN ('Expense', 'Deposit')),
                        transDate DATE DEFAULT SYSDATE,
                        amount NUMBER(12,4) NOT NULL CHECK(amount > 0),
                        accID NUMBER NOT NULL ,
                        CONSTRAINT fk_Transaction FOREIGN KEY (accID) REFERENCES ACCOUNT(accID));
                        



